--TRAINERGENERATORSTART--
--This is autogenerated code. Changing code in this block will
--get erased and rewritten if you regenerate the trainer code

--Uncomment the following line if this is a Cheat Table format trainer and you don't want CE to show (Tip, save as .CETRAINER alternatively)
hideAllCEWindows()

RequiredCEVersion=7.3
if (getCEVersion==nil) or (getCEVersion()&lt;RequiredCEVersion) then
  messageDialog('Please install Cheat Engine '..RequiredCEVersion, mtError, mbOK)
  closeCE()
end
addresslist=getAddressList()
memrec0=addresslist.getMemoryRecordByID(0)

memrec0_hotkey0=memrec0.getHotkeyByID(0)

function onHotkey0(Hotkey)
  --Executed before the hotkey is handled
  CETrainer.CHEAT0.setActive(true, 1500)
  if gPlaySoundOnAction then
    playSound(gActivateSound)
  end
end

memrec0_hotkey0.onHotkey=onHotkey0
CETrainer.SEPERATOR.Visible=false

getAutoAttachList().add("FIFA22.exe")
gPlaySoundOnAction=false
CETrainer.fixDPI() --remove this if you have already taken care of DPI issues yourself
CETrainer.show()
function AboutClick()
  showMessage(gAboutText)
end
gAboutText=[[This trainer was made by Cheat Engine www.cheatengine.org]]

function CloseClick()
  --called by the close button onClick event, and when closing the form
  closeCE()
  return caFree --onClick doesn't care, but onClose would like a result
end

--TRAINERGENERATORSTOP--