name: Run PowerShell build scrip
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2

      - name: Build
        run: ./build.ps1
        shell: pwsh

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: CHANGELOG
          tag_name: v0.0.1
          draft: false
          prerelease: false
          files: |
            target/release/fuck-ea

      - name: Artifact Production
        uses: actions/upload-artifact@v1
        with:
          name: release-build-artifact.zip
          path: target/release/fuck-ea

