name: Build Executable file

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  release:
    types: [ "published" ]

# temp workaround, because github actions suck...
env:
  VERSION: 0.0.2

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Print Variables
        run: |
          echo "github.head_ref: '${{ github.head_ref }}'"
          echo "github.head_sha: '${{ github.head_sha }}'"
          echo "github.ref_name: '${{ github.ref_name }}'"
          echo "env.VERSION: '${{ env.VERSION }}'"
        shell: pwsh

      - name: Install from PSGallery
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
          Install-Module -Name ps2exe
        shell: pwsh

      - name: Build executable
        run: |
          Invoke-ps2exe `
            -noOutput -noVisualStyles `
            -inputFile fuck-ea.ps1 `
            -version ${{ env.VERSION }} `
            -iconFile fuck-ea.ico `
            -title "Fuck EA" `
            -outputFile "fuck-ea_v${{ env.VERSION }}.exe"
        shell: pwsh

      - name: Artifact Production Build
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact.zip
          path: fuck-ea_v${{ env.VERSION }}.exe
