name: Build Executable file

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install from PSGallery
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
          Install-Module -Name ps2exe
        shell: pwsh

      - name: Build executable
        run: |
          Invoke-ps2exe `
            -noOutput -noVisualStyles `
            -inputFile fuck-ea.ps1 `
            -version  `
            -iconFile fuck-ea.ico `
            -title "Fuck EA" `
            -outputFile "fuck-ea_${{ github.head_ref }}.exe"
        shell: pwsh

      - name: Artifact Production Build
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact.zip
          path: fuck-ea_${{ github.head_ref }}.exe
