name: Release Executable

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  release:
    types: [ "published" ]

# temp workaround, because github actions suck...
env:
  VERSION: 0.0.2

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Print Variables
        run: |
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.head_sha: ${{ github.head_sha }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "env.VERSION: '${{ env.VERSION }}'"
        shell: powershell

      - name: Prepare changelog
        id: changeloging
        uses: mikepenz/release-changelog-builder-action@v2.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install from PSGallery
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
          Install-Module -Name ps2exe
        shell: powershell

      - name: Build executable
        run: |
          Invoke-ps2exe `
            -noOutput -noVisualStyles `
            -inputFile fuck-ea.ps1 `
            -version ${{ env.VERSION }} `
            -iconFile fuck-ea.ico `
            -title "Fuck EA" `
            -outputFile "fuck-ea_v${{ env.VERSION }}.exe"
        shell: powershell

      - name: Make Release Page
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.changeloging.outputs.changelog }}
          tag_name: v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            fuck-ea_v${{ env.VERSION }}.exe

      - name: Artifact Production Build
        uses: actions/upload-artifact@v2
        with:
          name: release-build-artifact.zip
          path: fuck-ea_v${{ env.VERSION }}.exe
